apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ printf "%s-operatorgroup" .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
spec:
{{- with .Values.additionalNamespaces }}
  targetNamespaces:
    {{ toYaml . }}
{{- end }}
  upgradeStrategy: Default
