apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.operatorGroup.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  channel: {{ .Values.catalog.channel }}
  installPlanApproval: {{ .Values.install.installPlanApproval }}
  name: {{ .Values.name }}
  source: {{ .Values.catalog.source }}
  sourceNamespace: {{ .Values.catalog.sourceNamespace }}
