# Default values for openshift-servicemesh-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jaeger:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  overrideOperatorNamespace: openshift-distributed-tracing

kiali:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # overrideOperatorNamespace: openshift-distributed-tracing

istio:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # overrideOperatorNamespace: openshift-distributed-tracing
