---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-operator.credentialName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "80"
type: Opaque
stringData:
  {{- toYaml .Values.provider.credentialData | nindent 2 }}
