---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-operator.credentialName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- toYaml .Values.provider.credentialData | nindent 2 }}
